apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      run: api
  replicas: 2
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api
        image: nokamoto13/kubernetes-crd-infrastructure-api:cc970db703fad68b325d00167a5fa6fcf12687ec        
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
