name: Build
on: [push]
jobs:

  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Make
      run: |
        make

  docker-build:
      name: Build docker
      runs-on: ubuntu-latest
      needs: build
      steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Make
        run: |
          echo ${DOCKERHUB_PASSWORD} | docker login --username nokamoto13 --password-stdin
          make docker-build IMG=nokamoto13/kubernetes-crd-infrastructure-api:${GITHUB_SHA}
          make docker-push IMG=nokamoto13/kubernetes-crd-infrastructure-api:${GITHUB_SHA}
        env:
          DOCKERHUB_PASSWORD: ${ secrets.DOCKERHUB_PASSWORD }
